### PR TITLE
feat: added footer component

### LINKED ISSUE #249: [Feature]: Styling and positioning the imprint, privacy policy and terms of use links
### Contact Details

_No response_

### What do you like to be improved?

- [ ] Positioning and styling the new imprint, terms of use and privacy policy links on the bottom of root.tsx

### PR DESCRIPTION
**Pull request by sstenz**
## List issues that are affected

close #249 

## Checklist

- as always pushed without tests

### CODE REVIEW

**Review by nac62116 — CHANGES_REQUESTED** [review]
@sstenz 
Looks good Sirko, thanks! ;)

Only thing is, that the footer is not shown on:
- profile/$username/settings/general
- organization/$slug/settings/general
As this concerns legal stuff, we need to be precise here.

Could you please find a way to make the footer visible on these pages?

**Comment by sstenz** [comment]
@nac62116 

I've been thinking about that, too. It's difficult because we use the same layout in all pages.

Is there a way to pass a class from the pages that we put in the body-tag in app/root.tsx?

**Comment by nac62116** [comment]
@sstenz 

I understand the problem.

What about either...
- ...collapsing the settings/general footer when scrolled to the end of page
or something like you mentioned...
- ...adding a bottom margin depending on the location (we can gather the location inside root.tsx)

**Review by nac62116 — APPROVED** [review]

**Comment by nac62116** [comment]
@sstenz 

Fixed it. No further action required.

**Pull request merged**
