### PR TITLE
Update index.func.tsx

### PR DESCRIPTION
**Pull request by olicoding**
Suggested changes includes a beforeEach() block to reset the application state before each test, and a try-catch block to catch any errors that might occur during the test.

## List issues that are affected

see [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

## Checklist

- [ ] Tests
- [ ] Documentation

## Request Reviewer (optional)

see [Requesting a pull request review](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review)

### CODE REVIEW

**Comment by phollome** [comment]
@olicoding Thanks for your work. Sadly I have an issue running the cypress test.
First it fails with:
```
Error: Webpack Compilation Error
./node_modules/@remix-run/web-fetch/src/fetch.js 120:13
Module parse failed: Unexpected token (120:13)
...
```
I think their is an issue with `fetch` used in browser and server context. But this can easily fixed by prevent importing `~/lib/utils/tests`.

After that it fails with:
```
supabaseUrl and supabaseKey are required to create a Supabase client! Find these under `Settings` > `API` in your Supabase dashboard.
```
Okay, means Cypress don't have the environment variables. Did you run the tests with special commands or do you have a special Cypress config? By default it doesn't load the environment variables from the `.env` file.

**Comment by olicoding** [comment]
updated commit at:
https://github.com/mint-vernetzt/community-platform/pull/771/commits/6122eecb53aab5fce3454dc031a02dc5b0fcb89d

**Comment by phollome** [comment]
@olicoding Do the tests run on your machine? Changing `~/lib/utils/tests` to `../lib/utils/tests/` doesn't work. `~` is a placeholder for `<root>/app` (see `tsconfig.json`). Beside that, it would be nice to changing cypress config to load .env file or persist running cypress tests with enironment variables from .env in package.json, like `npm run test:func:env` or something.

**Comment by olicoding** [comment]
Thank you for pointing it out. I see, the '~' refers to the path './app'. Noted. I apologise for any confusion. To clarify, I was not able to test the suggested changes on my own machine. My intention was simply to offer some general improvement suggestions based on my research and understanding of best practices for testing with Cypress.

About using the npm scripts to run the tests with environment variables from the .env file, it seems also like a good idea. I believe it would require the 'cross-env' library to set the environment variables before running the tests.

In the approach of loading the .env file into the Cypress configuration, you could use the dotenv library to load the variables, and then reference them in the Cypress config file without having to manually enter them again there. Here is the Cypress documentation on this: https://docs.cypress.io/guides/guides/environment-variables.html#Option-2-Using-a-library-to-load-variables-into-process.env

I hope this helps!

Wish you a merry Christmas eve tonight! 😄 🎄

**Pull request closed without merging**
